### ISSUE TITLE
Missing yalm in requirements

### ISSUE THREAD

**Issue by pbl007** [jcouto/wfield#1]
Hi, 

Got the following error
`(widefield) MacBook-Pro-173:~ pb$ wfield ncaas
Traceback (most recent call last):
  File "/opt/anaconda3/envs/widefield/bin/wfield", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/cli.py", line 525, in main
    CLIParser()
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/cli.py", line 52, in __init__
    getattr(self, args.command)()
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/cli.py", line 65, in ncaas
    from wfield.ncaas_gui import main as ncaas_gui
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 18, in <module>
    from .ncaas_utils import *
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_utils.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'`

` pip install pyyaml` did the trick. 

Will be great to add to requirements.
Thanks!

**Comment by jcouto** [comment]
Great, thanks!
