### ISSUE TITLE
AWS access key not in records

### ISSUE THREAD

**Issue by NathanTBurgess** [jcouto/wfield#13]
Hello! I am trying to upload your test data just to get the code running. I got this error:

Traceback (most recent call last):
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\boto3\s3\transfer.py", line 372, in upload_file
    future.result()
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\s3transfer\futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\s3transfer\futures.py", line 266, in result
    raise self._exception
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\s3transfer\tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\s3transfer\tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\s3transfer\tasks.py", line 348, in _main
    response = client.create_multipart_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\botocore\client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\botocore\client.py", line 1017, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\wfield\ncaas_utils.py", line 270, in run
    bucket.upload_file(self.filepath,
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\boto3\s3\inject.py", line 235, in bucket_upload_file
    return self.meta.client.upload_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\boto3\s3\inject.py", line 145, in upload_file
    return transfer.upload_file(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Natha\AppData\Local\Programs\Python\Python312\Lib\site-packages\boto3\s3\transfer.py", line 378, in upload_file
    raise S3UploadFailedError(
boto3.exceptions.S3UploadFailedError: Failed to upload C:/Users/Natha/Desktop/binary-ch1-002\binary-ch1-002.zip to wfield-preprocess/nathantbvtcv61482/inputs/binary-ch1-002/binary-ch1-002.zip: An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.

Is there something wrong with your AWS?

**Comment by jcouto** [comment]
Hi! That does look like the key does not have permissions?

 Was there any error before this one? Are there any folders listed on the right side of the GUI? I mean until you tried to upload the files. 

If your credentials are working in [neurocaas.org](https://neurocaas.org/)  maybe one can ask neurocaas@gmail.com for help here. 

I am happy to debug on the GUI side but don't have credentials myself at the moment so if you don't mind, let's first make sure all is good with the credentials.
