### ISSUE TITLE
Access denied to ncaas from despite grabbring right credentials 

### ISSUE THREAD

**Issue by pbl007** [jcouto/wfield#2]
Hi,

After completing for the first time the gui opened by `wfield ncass`, I get access denied with the following error:

`(widefield) MacBook-Pro-173:~ pb$ wfield ncaas
Connected to Amazon Web Services
Using buckets: cshl-wfield-locanmf, wfield-preprocess
Could not connect to NeuroCAAS, check credentials.
Got credentials from the website, you can close this window.
Saved AWS keys.
Connected to Amazon Web Services
Using buckets: cshl-wfield-locanmf, wfield-preprocess
Traceback (most recent call last):
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 1491, in main
    wind = NCAASwrapper(folder = folder)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 550, in __init__
    self.aws_view = AWSView(config, parent=self)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 1220, in __init__
    self.update_files()
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 1227, in update_files
    awsfiles = s3_ls(self.s3,self.bucketnames)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_utils.py", line 208, in s3_ls
    for l in list(bucket.objects.all()):
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/widefield/bin/wfield", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/cli.py", line 525, in main
    CLIParser()
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/cli.py", line 52, in __init__
    getattr(self, args.command)()
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/cli.py", line 67, in ncaas
    ncaas_gui(args.foldername)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 1499, in main
    wind = NCAASwrapper(folder = folder)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 550, in __init__
    self.aws_view = AWSView(config, parent=self)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 1220, in __init__
    self.update_files()
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_gui.py", line 1227, in update_files
    awsfiles = s3_ls(self.s3,self.bucketnames)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/wfield/ncaas_utils.py", line 208, in s3_ls
    for l in list(bucket.objects.all()):
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/anaconda3/envs/widefield/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
`

**Comment by jcouto** [comment]
Thanks for letting us know, this turned out to be more difficult to solve than we anticipated but we are very close.  It is related to some permission and folder structure changes in a recent update of the website.  I'll update soon.
